config/routes.rb
Zxc::Application.routes.draw do
  resources :posts, :path => "res", :except => [:update, :edit]
  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  
  attr_accessible :content, :email, :name, :post_id, :subject, :picture
  before_save :set_name
  before_save :sage
  validates :content, :presence => true
  validates_attachment :picture, 
     :content_type => { :content_type =>  ['image/jpeg', 'image/png']},
     :size => { :in => 0..3.megabytes }

  has_attached_file :picture, 
         :styles => { :small => "150x150>"}
  has_many :comments, :class_name => "Post", :dependent => :destroy
  belongs_to :post, :class_name => "Post", :foreign_key => :post_id 
  scope :threads, where(:post_id => nil).order('updated_at DESC')
  

  protected
    def set_name
      self.name = "Anonymous" if self.name.blank? 
    end

    def sage
      unless self.post_id.nil?
        unless self.email == "sage"
          op_post = Post.find(self.post_id)
          op_post.updated_at = Time.now
          op_post.save
        end  
      end  
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from ActiveRecord::RecordNotFound do
    redirect_to root_url 
  end	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @posts = Post.threads

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end
=begin  
  def edit
    @post = Post.find(params[:id])
  end
=end
  def create
    attach = params[:attach].nil? || params[:post][:post_id].blank?
    if attach
      params[:post][:post_id] = nil 
      @post = Post.create(params[:post])
    else
      parent = Post.find(params[:post][:post_id])
      @post = Post.create(params[:post])
    end  
    
    
    respond_to do |format|
      if @post.save 
        format.html { redirect_to parent || @post, notice: 'Post was successfully created.' }
        format.json { render json: parent || @post, status: :created, location: parent || @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

=begin  
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end
=end 
 
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def model(res = nil)
    if res
      Post.new(:post_id => res.id) 
    else
      Post.new
    end  	
  end
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Zxc"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    %link(href="images/favicon.ico" rel="shortcut icon")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114")

  %body
    
    .span12
      %h1.title ZXC
    
    .span12 
      = render :partial => 'posts/form' 
    = yield 
    
    
    

app/views/posts/_comment.html.haml
.span12.row-fluid
  -comments.each do |post|
    .span12
      %table.table
        %tr
          %td=post.subject
          %td=post.name
          %td=post.updated_at
          %td='№' + post.id.to_s
          %td= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger'
    .span12
      .span8
        =post.content
      .span4
        - if !post.picture_file_name.nil? 
          =image_tag post.picture.url(:small) 
     

app/views/posts/_form.html.haml
= form_for model(@post || nil), :html => { :class => 'form-horizontal', :multipart => true } do |f|
  -unless @post.nil?
    -if @post.errors.any?
      #error_explanation
        %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
        %ul
          - @post.errors.full_messages.each do |msg|
            %li= msg

  .control-group
    = f.label "Имя", :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.hidden_field :post_id  
  .control-group
    = f.label "E-mail", :class => 'control-label'
    .controls
      = f.text_field :email, :class => 'text_field'
  .control-group
    = f.label "Тема", :class => 'control-label'
    .controls
      = f.text_field :subject, :class => 'text_field'
  .control-group
    = label_tag "К треду", nil, :class => 'control-label'
    .controls
      = check_box_tag(:attach)    
  .control-group
    = f.label "Комментарий", :class => 'control-label'
    .controls
      = f.text_area :content, :cols => "60", :rows => "15", :class => 'text_area'
  .control-group    
    = f.label "Изображение", :class => 'control-label'
    .controls
      = f.file_field :picture
  .form-actions
    = f.submit "Отправить", :class => 'btn btn-primary'

app/views/posts/index.html.haml
.span12.row-fluid
  -@posts.each do |post|
    .span12
      %table.table
        %tr
          %td=post.subject
          %td=post.name
          %td=post.updated_at
          %td='№' + post.id.to_s
          %td=link_to '>>>', post
          %td= link_to 'Destroy', post, :confirm => 'Are you sure?', :method => :delete, :class => 'btn btn-mini btn-danger'
    .span12
      .span8
        =post.content    
      .span4
        - if !post.picture_file_name.nil?  
          =image_tag post.picture.url(:small) 
      

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
.span12.row-fluid
  .span12
    %table.table
      %tr
        %td
          %h4=@post.subject
        %td=@post.name
        %td=@post.updated_at
        %td='№' + @post.id.to_s
  
  .span12
    .span8
      =@post.content
    .span4
      - if !@post.picture_file_name.nil?  
        =image_tag @post.picture.url(:small) 
  

= render :partial => 'posts/comment', :locals => {:comments => @post.comments} 


= link_to 'Back', posts_path, {:class => 'btn pull-right'} 